#!/usr/bin/env bash
# ============================================================
# Pi Container — Entrypoint
# ============================================================
# Auto-generated by pi-container.
# Do not edit — changes will be overwritten on next build.
# ============================================================
set -eo pipefail

PI_HOME="/home/pi-user/.pi/agent"
TEAM_EXT_DIR="/opt/pi-extensions"
HOST_UID="${HOST_UID:-1000}"
HOST_GID="${HOST_GID:-1000}"

# ── Match pi-user UID/GID to host user ──────────────────
if [ "$(id -u pi-user)" != "${HOST_UID}" ]; then
  groupmod -g "${HOST_GID}" pi-user 2>/dev/null || true
  usermod -u "${HOST_UID}" -g "${HOST_GID}" pi-user 2>/dev/null || true
fi

# ── Ensure directory structure exists ──────────────────
mkdir -p "${PI_HOME}/sessions"
mkdir -p "${PI_HOME}/extensions"
mkdir -p "${PI_HOME}/npm"
mkdir -p "${PI_HOME}/git"
mkdir -p "${PI_HOME}/prompts"
mkdir -p "${PI_HOME}/skills"

# ── Fix ownership of config directory ──────────────────
chown -R pi-user:pi-user "${PI_HOME}" 2>/dev/null || true

# ── Copy default settings if none exist ────────────────
PI_SETTINGS="${PI_HOME}/settings.json"
DEFAULT_SETTINGS="/opt/pi/default-settings.json"
if [ ! -f "${PI_SETTINGS}" ]; then
  cp "${DEFAULT_SETTINGS}" "${PI_SETTINGS}"
  chown pi-user:pi-user "${PI_SETTINGS}" 2>/dev/null || true
fi

# ── Link team extensions ───────────────────────────────
# Extensions baked into the image are symlinked into the config
# directory so pi auto-discovers them. Won't overwrite if the
# user has an extension with the same name.
if [ -d "${TEAM_EXT_DIR}" ]; then
  for ext in "${TEAM_EXT_DIR}"/*; do
    [ -d "$ext" ] || continue
    name=$(basename "$ext")
    target="${PI_HOME}/extensions/${name}"

    if [ -e "$target" ] && [ ! -L "$target" ]; then
      # Real file/dir exists — user's own extension, don't overwrite
      true
    else
      # Remove stale symlink if it exists, then link fresh
      rm -f "$target" 2>/dev/null || true
      ln -s "$ext" "$target"
    fi
  done
fi

# ── Drop privileges and run command as pi-user ──────────
exec gosu pi-user "$@"