#!/usr/bin/env bash
# ============================================================
# Pi Container — Entrypoint
# ============================================================
# Auto-generated by pi-container.
# Do not edit — changes will be overwritten on next build.
# ============================================================
set -eo pipefail

PI_HOME="/home/pi-user/.pi"
PI_AGENT_HOME="${PI_HOME}/agent"
HOST_UID="${HOST_UID:-1000}"
HOST_GID="${HOST_GID:-1000}"

# ── Match pi-user UID/GID to host user ──────────────────
if [ "$(id -u pi-user)" != "${HOST_UID}" ]; then
  groupmod -g "${HOST_GID}" pi-user 2>/dev/null || true
  usermod -u "${HOST_UID}" -g "${HOST_GID}" pi-user 2>/dev/null || true
fi

# ── Fix ownership of config directory ──────────────────
chown -R pi-user:pi-user "${PI_HOME}" 2>/dev/null || true

# ── Copy default settings if none exist ────────────────
PI_SETTINGS="${PI_AGENT_HOME}/settings.json"
DEFAULT_SETTINGS="/opt/pi/default-settings.json"
if [ ! -f "${PI_SETTINGS}" ]; then
  cp "${DEFAULT_SETTINGS}" "${PI_SETTINGS}"
  chown pi-user:pi-user "${PI_SETTINGS}" 2>/dev/null || true
fi

# ── Install team package ───────────────────────────────
# The default pi-container package (extensions, themes, etc.)
# is baked into the image at /opt/pi-package. Install it so
# pi discovers its resources and registers the theme.
gosu pi-user pi install /opt/pi-package

# ── Drop privileges and run command as pi-user ──────────
exec gosu pi-user "$@"