// ============================================================
// Tests for templates.ts — Dockerfile and entrypoint generation
// ============================================================

import { describe, it, expect } from "vitest";
import { generateDockerfile, generateEntrypoint } from "./templates";
import { PiContainerConfig } from "./config";

function makeConfig(overrides: Partial<PiContainerConfig> = {}): PiContainerConfig {
  return {
    piVersion: "0.75.5",
    imageTag: "pi-agent:0.75.5",
    configDir: "/home/user/.pi/agent",
    containerDir: "/project/.pi-container",
    projectDir: "/project",
    envFile: "",
    extensions: [],
    hasPackages: false,
    hasSettings: false,
    ...overrides,
  };
}

describe("generateDockerfile", () => {
  it("includes the pinned pi version in ARG", () => {
    const config = makeConfig({ piVersion: "0.75.5" });
    const df = generateDockerfile(config);

    expect(df).toContain("ARG PI_VERSION=0.75.5");
  });

  it("uses multi-stage build", () => {
    const config = makeConfig();
    const df = generateDockerfile(config);

    expect(df).toContain("FROM node:22-bookworm-slim AS builder");
    expect(df).toContain("FROM node:22-bookworm-slim AS runtime");
  });

  it("installs pi in builder stage", () => {
    const config = makeConfig();
    const df = generateDockerfile(config);

    expect(df).toContain("npm install -g --ignore-scripts @earendil-works/pi-coding-agent@${PI_VERSION}");
  });

  it("installs runtime OS dependencies", () => {
    const config = makeConfig();
    const df = generateDockerfile(config);

    expect(df).toContain("git");
    expect(df).toContain("gosu");
  });

  it("creates pi-user", () => {
    const config = makeConfig();
    const df = generateDockerfile(config);

    expect(df).toContain("useradd -m -s /bin/bash pi-user");
  });

  it("copies pi from builder", () => {
    const config = makeConfig();
    const df = generateDockerfile(config);

    expect(df).toContain("COPY --from=builder /usr/local/lib/node_modules");
  });

  it("copies extensions, packages, settings, and entrypoint", () => {
    const config = makeConfig();
    const df = generateDockerfile(config);

    expect(df).toContain("COPY extensions/ /opt/pi-extensions/");
    expect(df).toContain("COPY --from=builder /build/packages /opt/pi-packages");
    expect(df).toContain("COPY entrypoint.sh /opt/pi/entrypoint.sh");
    expect(df).toContain("COPY settings/default-settings.json /opt/pi/default-settings.json");
  });

  it("sets workspace and entrypoint", () => {
    const config = makeConfig();
    const df = generateDockerfile(config);

    expect(df).toContain("WORKDIR /workspace");
    expect(df).toContain('ENTRYPOINT ["/opt/pi/entrypoint.sh"]');
    expect(df).toContain('CMD ["pi"]');
  });

  it("includes do-not-edit header", () => {
    const config = makeConfig();
    const df = generateDockerfile(config);

    expect(df).toContain("Auto-generated by pi-container");
    expect(df).toContain("Do not edit");
  });

  it("uses custom pi version", () => {
    const config = makeConfig({ piVersion: "1.0.0" });
    const df = generateDockerfile(config);

    expect(df).toContain("ARG PI_VERSION=1.0.0");
  });

  it("injects pi version in all ARG lines", () => {
    // Dockerfile has two ARG PI_VERSION lines (builder and runtime)
    const config = makeConfig({ piVersion: "2.0.0" });
    const df = generateDockerfile(config);

    // Both ARG lines should have the same version
    const argLines = df.split("\n").filter((line: string) => line.startsWith("ARG PI_VERSION="));
    expect(argLines.length).toBe(2);
    expect(argLines[0]).toBe("ARG PI_VERSION=2.0.0");
    expect(argLines[1]).toBe("ARG PI_VERSION=2.0.0");
  });
});

describe("generateEntrypoint", () => {
  it("starts with bash shebang", () => {
    const config = makeConfig();
    const sh = generateEntrypoint(config);

    expect(sh.startsWith("#!/usr/bin/env bash")).toBe(true);
  });

  it("sets pipefail", () => {
    const config = makeConfig();
    const sh = generateEntrypoint(config);

    expect(sh).toContain("set -eo pipefail");
  });

  it("matches UID/GID to host user", () => {
    const config = makeConfig();
    const sh = generateEntrypoint(config);

    expect(sh).toContain("groupmod");
    expect(sh).toContain("usermod");
    expect(sh).toContain("${HOST_UID:-1000}");
    expect(sh).toContain("${HOST_GID:-1000}");
  });

  it("creates pi config directory structure", () => {
    const config = makeConfig();
    const sh = generateEntrypoint(config);

    expect(sh).toContain('"${PI_HOME}/sessions"');
    expect(sh).toContain('"${PI_HOME}/extensions"');
    expect(sh).toContain('"${PI_HOME}/npm"');
    expect(sh).toContain('"${PI_HOME}/git"');
  });

  it("fixes ownership of config directory", () => {
    const config = makeConfig();
    const sh = generateEntrypoint(config);

    expect(sh).toContain("chown -R pi-user:pi-user");
  });

  it("copies default settings if none exist", () => {
    const config = makeConfig();
    const sh = generateEntrypoint(config);

    expect(sh).toContain('"${PI_HOME}/settings.json"');
    expect(sh).toContain("/opt/pi/default-settings.json");
    expect(sh).toContain('if [ ! -f "${PI_SETTINGS}" ]; then');
  });

  it("links team extensions respecting existing ones", () => {
    const config = makeConfig();
    const sh = generateEntrypoint(config);

    expect(sh).toContain('"${TEAM_EXT_DIR}"');
    expect(sh).toContain("ln -s");
    // Should NOT overwrite user's own extensions
    expect(sh).toContain('[ ! -L "$target" ]');
  });

  it("drops privileges with gosu", () => {
    const config = makeConfig();
    const sh = generateEntrypoint(config);

    expect(sh).toContain('exec gosu pi-user "$@"');
  });

  it("is valid bash (no template interpolation artifacts)", () => {
    const config = makeConfig();
    const sh = generateEntrypoint(config);

    // Should not contain JS template literal syntax
    expect(sh).not.toContain("${piVersion}");
    expect(sh).not.toContain("${config.");
    // Should not contain TypeScript/JS artifacts
    expect(sh).not.toContain("undefined");
  });
});